### ISSUE TITLE
[FEAT] 로티 메인뷰 구현

### ISSUE THREAD

**Issue by YoonAh-dev** [TeamCatchMe/CatchMe-iOS-Dungeon#1]
## 💡 Issue
로티 메인뷰를 구현할 겁니다.

## 📝  todo
- [x] 로티 넣어서 배경 구현해보기
- [x] page Control custom 하기
- [x] 옆으로 스와이프하면서 내용 바꾸는거 구현하기
